const quotes = [
  {
    q: "I find that the harder I work, the more luck I seem to have.",
    qA: thomasJefferosn,
    aDetails: `Thomas Jefferosn- 3rd U.S. President"`,
    isFav: localStorage.getItem("q0isFav") || "no",
    agreed: localStorage.getItem("q0Agreed") || 0,
  },
  {
    q: "Everything you've ever wanted is sitting on the other side of fear.",
    qA: georgeAddair,
    aDetails: `George Addair- Philosopher`,
    isFav: localStorage.getItem("q1isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Believe you can and you're halfway there.",
    qA: theodoreRoosevelt,
    aDetails: `Theodore Roosevelt- 26th U.S. President`,
    isFav: localStorage.getItem("q2isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "All the world’s a stage, and all the men and women merely players.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "A rose by any other name would smell as sweet.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "All that glitters is not gold.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Cowards die many times before their deaths; the valiant never taste of death but once.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Give me my robe, put on my crown; I have Immortal longings in me.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "There is nothing either good or bad, but thinking makes it so.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Better three hours too soon than a minute too late.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "All is fair in love and war.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "All the world’s a stage, and all the men and women merely players.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "What’s done is done.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: " Parting is such sweet sorrow.",
    qA: shakespeare,
    aDetails: `Shakespeare- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten. Don’t let yourself be lulled into inaction.",
    qA: billGates,
    aDetails: `Bill Gates- Ex CEO-MS`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I think it is possible for ordinary people to choose to be extraordinary.",
    qA: elon,
    aDetails: `Elon Musk- Businessman`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "If something is important enough, even if the odds are against you, you should still do it.",
    qA: elon,
    aDetails: `Elon Musk- Businessman`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I could either watch it happen or be a part of it.",
    qA: elon,
    aDetails: `Elon Musk- Businessman`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.",
    qA: lutherKing,
    aDetails: `Luther King- Activist`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I think therefore I am.",
    qA: reneDescartes,
    aDetails: `Rene Descartes- Philosopher`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Keep your friends close, but your enemies closer.",
    qA: michaelCorleone,
    aDetails: `Michael Corleone- Fictional character`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Knowledge is power.",
    qA: francisBacon,
    aDetails: `Francis Bacon- Chancellor`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Speak softly and carry a big stick.",
    qA: theodoreRoosevelt,
    aDetails: `Theodore Roosevelt- 26th U.S. President`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Three can keep a secret, if two of them are dead.",
    qA: benjaminFranklin,
    aDetails: `Benjamin Franklin- Polymath`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Two roads diverged in a wood, and I, I took the one less travelled by, and that has made all the difference.",
    qA: robertFrost,
    aDetails: `Robert Frost- Poet`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "No one can make you feel inferior without your consent.",
    qA: eleanorRoosevelt,
    aDetails: `Eleanor Roosevelt- Activist`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "You can fool all of the people some of the time, and some of the people all of the time, but you can't fool all of the people all of the time.",
    qA: abrahamLincoln,
    aDetails: `Abraham Lincoln- 6th U.S. President`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "It is not a lack of love, but a lack of friendship that makes unhappy marriages.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "And those who were seen dancing were thought to be insane by those who could not hear the music.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "You have your way. I have my way. As for the right way, the correct way, and the only way, it does not exist.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "He who has a why to live for can bear almost any how.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "In heaven, all the interesting people are missing.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "There are no facts, only interpretations.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "The individual has always had to struggle to keep from being overwhelmed by the tribe. If you try it, you will be lonely often, and sometimes frightened. But no price is too high to pay for the privilege of owning yourself.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I cannot believe in a God who wants to be praised all the time.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions; they cease to be mind.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I am a forest, and a night of dark trees: but he who is not afraid of my darkness, will find banks full of roses under my cypresses.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "The higher we soar the smaller we appear to those who cannot fly.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "The thought of suicide is a great consolation: by means of it one gets through many a dark night.",
    qA: friedrichNietzsche,
    aDetails: `Friedrich Nietzsche- Philosopher & Critic`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "Don't bend; don't water it down; don't try to make it logical; don't edit your own soul according to the fashion. Rather, follow your most intense obsessions mercilessly.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "A book must be the axe for the frozen sea within us.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I think we ought to read only the kind of books that wound or stab us. If the book we're reading doesn't wake us up with a blow to the head, what are we reading for?  A book must be the axe for the frozen sea within us. That is my belief.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I am free and that is why I am lost.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "A First Sign of the Beginning of Understanding is the Wish to Die.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "You do not need to leave your room. Remain sitting at your table and listen. Do not even listen, simply wait, be quiet, still and solitary. The world will freely offer itself to you to be unmasked, it has no choice, it will roll in ecstasy at your feet.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I have the true feeling of myself only when I am unbearably unhappy.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "By believing passionately in something that still does not exist, we create it. The nonexistent is whatever we have not sufficiently desired.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "𝐏𝐚𝐭𝐡𝐬 𝐚𝐫𝐞 𝐦𝐚𝐝𝐞 𝐛𝐲 𝐰𝐚𝐥𝐤𝐢𝐧𝐠.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I never wish to be easily defined. I’d rather float over other people’s minds as something strictly fluid and non-perceivable; more like a transparent, paradoxically iridescent creature rather than an actual person.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "I usually solve problems by letting them devour me.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
  {
    q: "By imposing too great a responsibility, or rather, all responsibility, on yourself, you crush yourself.",
    qA: franzKafka,
    aDetails: `Franz Kafka- Writer`,
    isFav: localStorage.getItem("q3isFav") || "no",
    agreed: localStorage.getItem("q1Agreed") || 0,
  },
];
